package com.views;

import com.DAO.CompraDAO;
import com.model.Producto;
import com.model.ReporteCompra;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irvingjose
 */
public class HistorialCompras extends javax.swing.JPanel {

    private DefaultTableModel modeloCompras;
    private final CompraDAO compraDAO = new CompraDAO();
    
    public HistorialCompras() {
        initComponents();
        configurarTabla();
        cargarReporteCompras();
    }

    public void configurarTabla() {
        String[] columnNames = {"Folio", "Fecha", "Proveedor", "Empleado", "Producto" , "Cantidad", "Costo_U","Total"};
    
        this.modeloCompras = new DefaultTableModel(columnNames, 0) {
            // Hacemos que la tabla no sea editable directamente
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tablereportes.setModel(this.modeloCompras);
        tablereportes.getTableHeader().setResizingAllowed(true);

        tablereportes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablereportes.getColumnModel().getColumn(1).setPreferredWidth(70);
        tablereportes.getColumnModel().getColumn(2).setPreferredWidth(107);
        tablereportes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tablereportes.getColumnModel().getColumn(4).setPreferredWidth(95); 
        tablereportes.getColumnModel().getColumn(5).setPreferredWidth(56);
        tablereportes.getColumnModel().getColumn(6).setPreferredWidth(52);
        tablereportes.getColumnModel().getColumn(7).setPreferredWidth(50);
    }
    
    public void cargarReporteCompras() {
        // Limpiar filas anteriores
        modeloCompras.setRowCount(0); 

        try {
            // 1. Obtener la lista de ReporteCompra usando el DAO (Consulta de 5 tablas)
            List<ReporteCompra> reportes = compraDAO.listarReporteDetalleCompras();

            // 2. Iterar sobre la lista y añadir cada reporte como una fila
            for (ReporteCompra rc : reportes) {
                Object[] rowData = new Object[8];
                rowData[0] = rc.getFolioC();
                rowData[1] = rc.getFechaDisplay();
                rowData[2] = rc.getNombreProveedor();
                rowData[3] = rc.getNombreEmpleado();
                rowData[4] = rc.getDescripcionProducto();
                rowData[5] = rc.getCantidad();
                rowData[6] = String.format("$%.2f", rc.getCostoUnitario()); // Formato de moneda
                rowData[7] = String.format("$%.2f", rc.getTotal());        // Total calculado

                modeloCompras.addRow(rowData);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el historial de compras: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablereportes = new javax.swing.JTable();
        pnlupdate = new javax.swing.JPanel();
        buttonupdate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 249, 235));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial y Detalle de Compras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(252, 249, 235));
        jScrollPane1.setBorder(null);

        tablereportes.setBackground(new java.awt.Color(252, 249, 235));
        tablereportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablereportes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 680, 300));

        pnlupdate.setBackground(new java.awt.Color(124, 123, 174));

        buttonupdate.setBackground(new java.awt.Color(124, 123, 174));
        buttonupdate.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttonupdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonupdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonupdate.setText("Actualizar");
        buttonupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonupdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlupdateLayout = new javax.swing.GroupLayout(pnlupdate);
        pnlupdate.setLayout(pnlupdateLayout);
        pnlupdateLayout.setHorizontalGroup(
            pnlupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        pnlupdateLayout.setVerticalGroup(
            pnlupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(pnlupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonupdateMouseClicked
        configurarTabla();
        cargarReporteCompras();
    }//GEN-LAST:event_buttonupdateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonupdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlupdate;
    private javax.swing.JTable tablereportes;
    // End of variables declaration//GEN-END:variables
}
