package com.views;

import com.DAO.ProductoDAO;
import com.model.Producto;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InventarioProducto extends javax.swing.JPanel {
    
    private DefaultTableModel modeloProducto;
    private ProductoDAO productoDAO = new ProductoDAO();

    public InventarioProducto() {
        initComponents();
        configurarTabla();
        cargarDatosTabla(); // Esto llenará la tabla al abrir el panel
    }
    
    public void configurarTabla() {
        String[] columnNames = {"ID", "Nombre", "Categoria", "U. Medida", "Stock" , "Precio C", "Precio V"};

        this.modeloProducto = new DefaultTableModel(columnNames, 0); 
        
        tableproductos.setModel(this.modeloProducto);
        tableproductos.getTableHeader().setResizingAllowed(true);

        tableproductos.getColumnModel().getColumn(0).setPreferredWidth(40);
        tableproductos.getColumnModel().getColumn(1).setPreferredWidth(130);
        tableproductos.getColumnModel().getColumn(2).setPreferredWidth(75);
        tableproductos.getColumnModel().getColumn(3).setPreferredWidth(85);
        tableproductos.getColumnModel().getColumn(4).setPreferredWidth(50); 
        tableproductos.getColumnModel().getColumn(5).setPreferredWidth(55);
        tableproductos.getColumnModel().getColumn(6).setPreferredWidth(55);
    }
    
    public void cargarDatosTabla() {
        try {
            List<Producto> lista = productoDAO.listarProductos();

            for (Producto p : lista) {
                modeloProducto.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getCategoria(),
                    p.getUnidad_medida(), 
                    p.getExitencia(),
                    p.getPrecio_c(),
                    p.getPrecio_v()
                });
            }
            tableproductos.setModel(modeloProducto);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void limpiarCampos() {
        fieldcodigo.setText("");
        fieldproducto.setText("");
        precioc.setText("");
        preciov.setText("");
        cantidadstock.setText(""); 

        if (categorias.getItemCount() > 0) {
            categorias.setSelectedIndex(0);
        }
        if (unidadmedidafield.getItemCount() > 0) {
            unidadmedidafield.setSelectedIndex(0);
        }
        
        fieldproducto.setEnabled(true);
        precioc.setEnabled(true);
        preciov.setEnabled(true);
        categorias.setEnabled(true);
        unidadmedidafield.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableproductos = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        pnleditar = new javax.swing.JPanel();
        buttonsave = new javax.swing.JLabel();
        pnleliminar = new javax.swing.JPanel();
        buttondelete = new javax.swing.JLabel();
        pnllimpiar = new javax.swing.JPanel();
        buttonclear = new javax.swing.JLabel();
        txtnombre = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JLabel();
        textcat = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JLabel();
        txtpreciov = new javax.swing.JLabel();
        txtprecioc = new javax.swing.JLabel();
        fieldproducto = new javax.swing.JTextField();
        fieldcodigo = new javax.swing.JTextField();
        categorias = new javax.swing.JComboBox<>();
        precioc = new javax.swing.JTextField();
        preciov = new javax.swing.JTextField();
        textunidadmedida = new javax.swing.JLabel();
        unidadmedidafield = new javax.swing.JComboBox<>();
        cantidadstock = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 249, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoria", "Precio Compra", "Precio Venta", "Stock"
            }
        ));
        tableproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 490, 150));

        separador.setForeground(new java.awt.Color(0, 0, 0));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 510, -1));

        pnleditar.setBackground(new java.awt.Color(124, 123, 174));

        buttonsave.setBackground(new java.awt.Color(124, 123, 174));
        buttonsave.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttonsave.setForeground(new java.awt.Color(255, 255, 255));
        buttonsave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsave.setText("GUARDAR");
        buttonsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnleditarLayout = new javax.swing.GroupLayout(pnleditar);
        pnleditar.setLayout(pnleditarLayout);
        pnleditarLayout.setHorizontalGroup(
            pnleditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnleditarLayout.setVerticalGroup(
            pnleditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(pnleditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 150, 25));

        pnleliminar.setBackground(new java.awt.Color(124, 123, 174));

        buttondelete.setBackground(new java.awt.Color(124, 123, 174));
        buttondelete.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttondelete.setForeground(new java.awt.Color(255, 255, 255));
        buttondelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttondelete.setText("ELIMINAR");
        buttondelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttondeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnleliminarLayout = new javax.swing.GroupLayout(pnleliminar);
        pnleliminar.setLayout(pnleliminarLayout);
        pnleliminarLayout.setHorizontalGroup(
            pnleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttondelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnleliminarLayout.setVerticalGroup(
            pnleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttondelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(pnleliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 25));

        pnllimpiar.setBackground(new java.awt.Color(124, 123, 174));

        buttonclear.setBackground(new java.awt.Color(124, 123, 174));
        buttonclear.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttonclear.setForeground(new java.awt.Color(255, 255, 255));
        buttonclear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonclear.setText("LIMPIAR");
        buttonclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonclearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnllimpiarLayout = new javax.swing.GroupLayout(pnllimpiar);
        pnllimpiar.setLayout(pnllimpiarLayout);
        pnllimpiarLayout.setHorizontalGroup(
            pnllimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnllimpiarLayout.setVerticalGroup(
            pnllimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(pnllimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 180, 150, 25));

        txtnombre.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtnombre.setText("Nombre:");
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 75, 25));

        txtcodigo.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtcodigo.setText("Codigo:");
        add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 75, 25));

        textcat.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        textcat.setText("Categoria:");
        add(textcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 75, 25));

        txtcantidad.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtcantidad.setText("Existencia:");
        add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 75, 25));

        txtpreciov.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtpreciov.setText("Precio Venta:");
        add(txtpreciov, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 25));

        txtprecioc.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtprecioc.setText("Precio Compra:");
        add(txtprecioc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, 25));

        fieldproducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldproducto.setBorder(null);
        add(fieldproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 25));

        fieldcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldcodigo.setBorder(null);
        add(fieldcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 25));

        categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura", "Otros" }));
        categorias.setBorder(null);
        add(categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 150, 25));

        precioc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioc.setBorder(null);
        add(precioc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 70, 25));

        preciov.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preciov.setBorder(null);
        add(preciov, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 70, 25));

        textunidadmedida.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        textunidadmedida.setText("Unidad de Medida:");
        add(textunidadmedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 25));

        unidadmedidafield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza", "kilogramo", "otro" }));
        unidadmedidafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadmedidafieldActionPerformed(evt);
            }
        });
        add(unidadmedidafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 175, 25));

        cantidadstock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadstock.setBorder(null);
        add(cantidadstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void tableproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductosMouseClicked
        int fila = tableproductos.getSelectedRow();

        if (fila == -1) {
            return;
        }

        try {
            // Obtención de Código, Nombre, Categoría, U. Medida)
            int codigo = (int) modeloProducto.getValueAt(fila, 0);
            String nombre = (String) modeloProducto.getValueAt(fila, 1);
            String categoria = (String) modeloProducto.getValueAt(fila, 2);
            String uMedida = (String) modeloProducto.getValueAt(fila, 3);

            // Obtener como Number y usar doubleValue()
            Number stock_num = (Number) modeloProducto.getValueAt(fila, 4);
            Number precioC_num = (Number) modeloProducto.getValueAt(fila, 5);
            Number precioV_num = (Number) modeloProducto.getValueAt(fila, 6);

            double precioC = precioC_num.doubleValue();
            double precioV = precioV_num.doubleValue();
            int stock = stock_num.intValue();

            // Rellenar los campos de la interfaz
            fieldcodigo.setText(String.valueOf(codigo));
            fieldproducto.setText(nombre);
            precioc.setText(String.valueOf(precioC));
            preciov.setText(String.valueOf(precioV));
            cantidadstock.setText("" + stock); 
            categorias.setSelectedItem(categoria);
            unidadmedidafield.setSelectedItem(uMedida);

            // No se pueden modificar
            fieldcodigo.setEnabled(false);
            cantidadstock.setEnabled(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos de la fila: " + ex.getMessage(), "Error de Lectura", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableproductosMouseClicked

    private void buttonsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsaveMouseClicked
        try {
            // VALIDACIÓN BÁSICA
            if (fieldproducto.getText().isEmpty() || precioc.getText().isEmpty() || preciov.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Rellena todos los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Verificamos que el usuario haya seleccionado un producto de la tabla
            if (fieldcodigo.isEnabled() || fieldcodigo.getText().equals("AUTOMÁTICO") || fieldcodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Para guardar cambios, primero selecciona un producto de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // RECOPILACIÓN DE DATOS
            Producto producto = new Producto();

            producto.setCodigo(Integer.parseInt(fieldcodigo.getText()));
            // Atributos modificables
            producto.setDescripcion(fieldproducto.getText());
            producto.setCategoria(categorias.getSelectedItem().toString());
            producto.setUnidad_medida(unidadmedidafield.getSelectedItem().toString());
            producto.setPrecio_c(Double.parseDouble(precioc.getText()));
            producto.setPrecio_v(Double.parseDouble(preciov.getText()));

            if (productoDAO.actualizarAtributosProducto(producto)) {
                JOptionPane.showMessageDialog(this, "Producto ACTUALIZADO con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el producto para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            limpiarCampos();
            configurarTabla();
            cargarDatosTabla();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato en Código o Precio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonsaveMouseClicked

    private void buttonclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonclearMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_buttonclearMouseClicked

    private void buttondeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttondeleteMouseClicked
        try {
            if (fieldcodigo.getText().isEmpty() || fieldcodigo.isEnabled()) {
                JOptionPane.showMessageDialog(this, "Selecciona un producto de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int codigoEliminar = Integer.parseInt(fieldcodigo.getText());

            int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de que deseas eliminar el producto con código " + codigoEliminar + "? Esta acción es irreversible y genera un registro de auditoría.", 
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                if (productoDAO.eliminarProducto(codigoEliminar)) {
                    JOptionPane.showMessageDialog(this, "Producto eliminado con éxito. Se registró en auditoría.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    configurarTabla();
                    cargarDatosTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el producto para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código de producto inválido. Asegúrate de que sea un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error SQL al eliminar: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttondeleteMouseClicked

    private void unidadmedidafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadmedidafieldActionPerformed

    }//GEN-LAST:event_unidadmedidafieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonclear;
    private javax.swing.JLabel buttondelete;
    private javax.swing.JLabel buttonsave;
    private javax.swing.JTextField cantidadstock;
    private javax.swing.JComboBox<String> categorias;
    private javax.swing.JTextField fieldcodigo;
    private javax.swing.JTextField fieldproducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnleditar;
    private javax.swing.JPanel pnleliminar;
    private javax.swing.JPanel pnllimpiar;
    private javax.swing.JTextField precioc;
    private javax.swing.JTextField preciov;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tableproductos;
    private javax.swing.JLabel textcat;
    private javax.swing.JLabel textunidadmedida;
    private javax.swing.JLabel txtcantidad;
    private javax.swing.JLabel txtcodigo;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JLabel txtprecioc;
    private javax.swing.JLabel txtpreciov;
    private javax.swing.JComboBox<String> unidadmedidafield;
    // End of variables declaration//GEN-END:variables
}
