package com.views;

import com.conexion.Conexion;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        SetImageLabel(logo,"src/main/resources/images/logo.jpg");
    }
    
    public void SetImageLabel(JLabel labelname, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth() ,labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.JPanel();
        fond = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usertext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        loginbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gb.setBackground(new java.awt.Color(255, 255, 255));
        gb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        fond.setText("jLabel1");
        gb.add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 450));

        jLabel1.setFont(new java.awt.Font("PT Sans", 1, 28)); // NOI18N
        jLabel1.setText("Iniciar Sesión");
        gb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        gb.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 70));

        jLabel2.setFont(new java.awt.Font("PT Sans", 1, 20)); // NOI18N
        jLabel2.setText("Usuario:");
        gb.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        usertext.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        usertext.setForeground(new java.awt.Color(204, 204, 204));
        usertext.setText("Ingrese su nombre de usuario");
        usertext.setBorder(null);
        usertext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertextMouseClicked(evt);
            }
        });
        gb.add(usertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 400, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        gb.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, -1));

        jLabel3.setFont(new java.awt.Font("PT Sans", 1, 20)); // NOI18N
        jLabel3.setText("Password:");
        gb.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        gb.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 400, -1));

        txtPassword.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        gb.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, 20));

        jPanel1.setBackground(new java.awt.Color(254, 222, 95));

        loginbutton.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        loginbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbutton.setText("LOGIN");
        loginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        gb.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 350, 120, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
        String usuarioIngresado = usertext.getText();
        String passwordIngresada = new String(txtPassword.getPassword());

        Connection tempConn = null;
    
        try {
        // INTENTAR LA CONEXIÓN CON LAS CREDENCIALES DEL USUARIO
        // Si PostgreSQL acepta la conexión, el usuario existe y la contraseña es correcta.
        tempConn = Conexion.getInstance().getConnection(usuarioIngresado, passwordIngresada);
        
        JOptionPane.showMessageDialog(this, "Bienvenido, " + usuarioIngresado);
        
        MenuFruit menu = new MenuFruit(usuarioIngresado); 
        menu.setVisible(true);
        this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de Login", JOptionPane.ERROR_MESSAGE);

        } finally {
            if (tempConn != null) {
                try {
                    tempConn.close();
                } catch (SQLException e) {
                    System.err.println("Error al cerrar la conexión de login: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_loginbuttonMouseClicked

    private void usertextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseClicked
        usertext.setForeground(Color.BLACK);
        usertext.setText("");
    }//GEN-LAST:event_usertextMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setForeground(Color.BLACK);
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fond;
    private javax.swing.JPanel gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginbutton;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField usertext;
    // End of variables declaration//GEN-END:variables
}
