package com.views;

import com.DAO.AuditoriaDAO;
import com.model.Auditoria;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class PestanaAuditoria extends javax.swing.JPanel {

    private DefaultTableModel modeloauditoria;
    private AuditoriaDAO auditoriadao;
    private Auditoria auditoria;

    public PestanaAuditoria() {
        initComponents();
        auditoriadao = new AuditoriaDAO();
        configurarTabla();
        cargarAuditorias();
    }

    public void configurarTabla() {
        String[] columnNames = {"ID", "Tabla Afectada", "Operacion", "UsuarioBD", "Fecha Auditoria"};

        this.modeloauditoria = new DefaultTableModel(columnNames, 0) {
            // Hacemos que la tabla no sea editable directamente
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaauditorias.setModel(this.modeloauditoria);
        tablaauditorias.getTableHeader().setResizingAllowed(true);

        tablaauditorias.getColumnModel().getColumn(0).setPreferredWidth(60);
        tablaauditorias.getColumnModel().getColumn(1).setPreferredWidth(155);
        tablaauditorias.getColumnModel().getColumn(2).setPreferredWidth(155);
        tablaauditorias.getColumnModel().getColumn(3).setPreferredWidth(155);
        tablaauditorias.getColumnModel().getColumn(4).setPreferredWidth(155);

    }

    public void cargarAuditorias() {
        // 1. Limpiar filas anteriores
        modeloauditoria.setRowCount(0);
        try {
            // 2. Obtener la lista de clientes activos
            List<Auditoria> auditorias = auditoriadao.obtenerAuditoria();
            // 3. Iterar sobre la lista y añadir cada cliente como una fila
            for (Auditoria au : auditorias) {
                Object[] rowData = new Object[5];
                rowData[0] = au.getId_a();
                rowData[1] = au.getNombretabla();
                rowData[2] = au.getOperacion();
                rowData[3] = au.getUsuariobd();
                rowData[4] = au.getFechaDisplay();

                modeloauditoria.addRow(rowData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar la lista de clientes: " + e.getMessage(),
                    "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaauditorias = new javax.swing.JTable();

        setBackground(new java.awt.Color(252, 249, 235));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Auditoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaauditorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaauditorias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaauditorias;
    // End of variables declaration//GEN-END:variables
}
