package com.views;

import com.DAO.ClienteDAO;
import com.DAO.ReporteDAO;
import com.model.Cliente;
import com.model.ReporteVenta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReporteVentas extends javax.swing.JPanel {

    private DefaultTableModel modeloreportes;
    private ReporteDAO reportedao;
    private ReporteVenta reporte;
    
    public ReporteVentas() {
        initComponents();
        reportedao = new ReporteDAO();
        configurarTabla();
        cargarReportes();
    }
    
    public void configurarTabla() {
        String[] columnNames = {"Fecha", "Folio", "Empleado", "Cliente", "Producto", "Cantidad","Costo_U", "Total Venta"};
    
        this.modeloreportes = new DefaultTableModel(columnNames, 0) {
            // Hacemos que la tabla no sea editable directamente
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tablaventas.setModel(this.modeloreportes);
        tablaventas.getTableHeader().setResizingAllowed(true);

        tablaventas.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaventas.getColumnModel().getColumn(1).setPreferredWidth(40);
        tablaventas.getColumnModel().getColumn(2).setPreferredWidth(110);
        tablaventas.getColumnModel().getColumn(3).setPreferredWidth(125);
        tablaventas.getColumnModel().getColumn(4).setPreferredWidth(110); 
        tablaventas.getColumnModel().getColumn(5).setPreferredWidth(70); 
        tablaventas.getColumnModel().getColumn(6).setPreferredWidth(70); 
        tablaventas.getColumnModel().getColumn(7).setPreferredWidth(75); 
        
    }
    
    public void cargarReportes() {
        // 1. Limpiar filas anteriores
        modeloreportes.setRowCount(0); 
        try {
            // 2. Obtener la lista de clientes activos
            List<ReporteVenta> reportes = reportedao.obtenerReporteVentasDetallado();
            // 3. Iterar sobre la lista y añadir cada cliente como una fila
            for (ReporteVenta reporte : reportes) {
                Object[] rowData = new Object[8];
                rowData[0] = reporte.getFechaDisplay();
                rowData[1] = reporte.getFolio_v();
                rowData[2] = reporte.getEmpleado();
                rowData[3] = reporte.getCliente();
                rowData[4] = reporte.getProducto();
                rowData[5] = reporte.getCantidad();
                rowData[6] = reporte.getPrecio_u();
                rowData[7] = reporte.getTotal_venta();

                modeloreportes.addRow(rowData);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar la lista de clientes: " + e.getMessage(), 
                "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlsearch = new javax.swing.JPanel();
        buttonsearch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 249, 235));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Nombre Empleado", "Nombre Cliente", "Producto Vendido", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 340));

        jLabel1.setText("Folio de Venta:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        pnlsearch.setBackground(new java.awt.Color(124, 123, 174));

        buttonsearch.setBackground(new java.awt.Color(124, 123, 174));
        buttonsearch.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttonsearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsearch.setText("Calcular Venta");
        buttonsearch.setToolTipText("");
        buttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlsearchLayout = new javax.swing.GroupLayout(pnlsearch);
        pnlsearch.setLayout(pnlsearchLayout);
        pnlsearchLayout.setHorizontalGroup(
            pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlsearchLayout.setVerticalGroup(
            pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(pnlsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 35, 140, 20));

        jLabel2.setText("Total Calculado");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel3.setText("----");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseClicked

    }//GEN-LAST:event_buttonsearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlsearch;
    private javax.swing.JTable tablaventas;
    // End of variables declaration//GEN-END:variables
}
