package com.views;

import com.DAO.ClienteDAO;
import com.DAO.ReporteDAO;
import com.model.Cliente;
import com.model.ReporteVenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReporteVentas extends javax.swing.JPanel {

    private DefaultTableModel modeloreportes;
    private ReporteDAO reportedao;
    private ReporteVenta reporte;
    
    public ReporteVentas() {
        initComponents();
        reportedao = new ReporteDAO();
        configurarTabla();
        cargarReportes();
    }
    
    public void configurarTabla() {
        String[] columnNames = {"Fecha", "Folio", "Empleado", "Cliente", "Producto", "Cantidad","Costo_U", "Total Venta"};
    
        this.modeloreportes = new DefaultTableModel(columnNames, 0) {
            // Hacemos que la tabla no sea editable directamente
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tablaventas.setModel(this.modeloreportes);
        tablaventas.getTableHeader().setResizingAllowed(true);

        tablaventas.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaventas.getColumnModel().getColumn(1).setPreferredWidth(40);
        tablaventas.getColumnModel().getColumn(2).setPreferredWidth(110);
        tablaventas.getColumnModel().getColumn(3).setPreferredWidth(125);
        tablaventas.getColumnModel().getColumn(4).setPreferredWidth(110); 
        tablaventas.getColumnModel().getColumn(5).setPreferredWidth(70); 
        tablaventas.getColumnModel().getColumn(6).setPreferredWidth(70); 
        tablaventas.getColumnModel().getColumn(7).setPreferredWidth(75); 
        
    }
    
    public void cargarReportes() {
        // 1. Limpiar filas anteriores
        modeloreportes.setRowCount(0); 
        try {
            // 2. Obtener la lista de clientes activos
            List<ReporteVenta> reportes = reportedao.obtenerReporteVentasDetallado();
            // 3. Iterar sobre la lista y añadir cada cliente como una fila
            for (ReporteVenta reporte : reportes) {
                Object[] rowData = new Object[8];
                rowData[0] = reporte.getFechaDisplay();
                rowData[1] = reporte.getFolio_v();
                rowData[2] = reporte.getEmpleado();
                rowData[3] = reporte.getCliente();
                rowData[4] = reporte.getProducto();
                rowData[5] = reporte.getCantidad();
                rowData[6] = reporte.getPrecio_u();
                rowData[7] = reporte.getTotal_venta();

                modeloreportes.addRow(rowData);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar la lista de clientes: " + e.getMessage(), 
                "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void calcularTotalDeVenta() {
        String folioTexto = txtFolioVenta.getText().trim();
        if (folioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un Folio de Venta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            lblTotalCalculado.setText("----");
            return;
        }
        
        try {
            int folio = Integer.parseInt(folioTexto);
            
            // Llama al método DAO que a su vez llama a la Función 4 SQL
            double total = reportedao.calcularTotalVenta(folio);
            
            if (total > 0) {
                lblTotalCalculado.setText("$ " + String.format("%,.2f", total));
            } else {
                 lblTotalCalculado.setText("FOLIO NO ENCONTRADO");
                 JOptionPane.showMessageDialog(this, 
                    "No se encontró el folio " + folio + " o la venta es cero.", 
                    "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El Folio debe ser un número entero válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            lblTotalCalculado.setText("ERROR");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error de Base de Datos al calcular total: " + ex.getMessage(), 
                "Error SQL", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            lblTotalCalculado.setText("ERROR DB");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCalcularVenta = new javax.swing.JPanel();
        buttonsearch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalCalculado = new javax.swing.JLabel();
        txtFolioVenta = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 249, 235));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Folio", "Nombre Empleado", "Nombre Cliente", "Producto Vendido", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 340));

        jLabel1.setText("Folio de Venta:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 25));

        btnCalcularVenta.setBackground(new java.awt.Color(124, 123, 174));

        buttonsearch.setBackground(new java.awt.Color(124, 123, 174));
        buttonsearch.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        buttonsearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsearch.setText("Calcular Venta");
        buttonsearch.setToolTipText("");
        buttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCalcularVentaLayout = new javax.swing.GroupLayout(btnCalcularVenta);
        btnCalcularVenta.setLayout(btnCalcularVentaLayout);
        btnCalcularVentaLayout.setHorizontalGroup(
            btnCalcularVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnCalcularVentaLayout.setVerticalGroup(
            btnCalcularVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(btnCalcularVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 35, -1, 25));

        jLabel2.setText("Total Calculado");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 35, -1, 25));

        lblTotalCalculado.setText("----");
        add(lblTotalCalculado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 35, -1, 25));
        add(txtFolioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 35, 100, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseClicked
        calcularTotalDeVenta();
    }//GEN-LAST:event_buttonsearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCalcularVenta;
    private javax.swing.JLabel buttonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalCalculado;
    private javax.swing.JTable tablaventas;
    private javax.swing.JTextField txtFolioVenta;
    // End of variables declaration//GEN-END:variables
}
